# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20170223_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='uuid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
