# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='node-ae0bb89c', max_length=20, unique=True)),
                ('host', models.CharField(max_length=200)),
                ('ipaddr', models.GenericIPAddressField()),
                ('system_info', jsonfield.fields.JSONField()),
                ('role', jsonfield.fields.JSONField()),
                ('component_info', jsonfield.fields.JSONField()),
                ('cpu', models.FloatField()),
                ('mem', models.FloatField()),
                ('disk', models.FloatField()),
                ('tags', jsonfield.fields.JSONField()),
                ('status', models.CharField(default='plain', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.Cluster', to_field='uuid')),
            ],
            options={
                'ordering': ('host',),
            },
        ),
    ]
