# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='uuid',
            field=models.CharField(default='node-1d89fe35', max_length=20, unique=True),
        ),
    ]
