# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='node',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='node',
            name='mem',
        ),
    ]
