# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='cluster-5f6c5f43', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('master', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=10)),
                ('proxy', models.CharField(max_length=30)),
                ('cluster_engine', models.CharField(default='kubernetes', max_length=20)),
                ('platform_info', jsonfield.fields.JSONField()),
                ('network_info', jsonfield.fields.JSONField()),
                ('metas', jsonfield.fields.JSONField()),
                ('capacity_info', jsonfield.fields.JSONField()),
                ('tags', jsonfield.fields.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
