# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_auto_20170222_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='uuid',
            field=models.CharField(default='cluster-1faf78c4', max_length=20, unique=True),
        ),
    ]
